### ISSUE TITLE
Ubuntu 16.04 compatiblity

### ISSUE THREAD

**Issue by gsedej** [marazmista/radeon-profile#78]
Hi. I am using radeon gpus on multiple systems, that all run Ubuntu 16.04 + newer kernel [*] + oibaf ppa [**].  I know 16.04 is old distro but it has great support via PPA (non-official updates)

I am not able to compile recent versions of radeon-profile, because of new qt5.6 reqs. I would probably have to install/compile whole qt5.6. 

Did someone managed to compile recent versions on 16.04?

[*] ubuntu kernel ppa, currently 4.14
[**] updated mesa to 17.x git

**Comment by Danysan1** [comment]
In case you can't give a way to install Qt5.6, the last version of radeon-profile that compiles without Qt5.6+QtCharts is https://github.com/marazmista/radeon-profile/tree/20161221
Some info won't be available (because it had not been implemented yet) and you will need to use it as root or use radeon-profile-demon.
